/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.sgbs.ui;
import br.com.sgbs.db.ConexaoMysql;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Roberto Coutinho
 */
public class RemoverDoador extends javax.swing.JFrame {

    /**
     * Creates new form AtualizarDetalhesDoador
     */
    public RemoverDoador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        IdDoadorjTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nomejTextField2 = new javax.swing.JTextField();
        nomePaijTextField3 = new javax.swing.JTextField();
        nomeMaejTextField4 = new javax.swing.JTextField();
        datajTextField5 = new javax.swing.JTextField();
        telefonejTextField6 = new javax.swing.JTextField();
        sexojTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        emailjTextField8 = new javax.swing.JTextField();
        grupoSangjTextField9 = new javax.swing.JTextField();
        cidadejTextField10 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        enderecojTextArea1 = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(340, 130));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("REMOVER DOADOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 6, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 741, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID do Doador");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 79, -1, -1));
        getContentPane().add(IdDoadorjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 79, 148, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgbs/img/search1.png"))); // NOI18N
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 76, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 108, 741, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nome Completo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 147, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nome do Pai");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 191, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nome da Mãe");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 235, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Data de Aniversário");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 279, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Número de Telefone");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 323, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Sexo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 367, -1, -1));

        nomejTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(nomejTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 144, 237, -1));

        nomePaijTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(nomePaijTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 188, 237, -1));

        nomeMaejTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(nomeMaejTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 232, 237, -1));

        datajTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        datajTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datajTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(datajTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 276, 215, -1));

        telefonejTextField6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        telefonejTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonejTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(telefonejTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 320, 210, -1));

        sexojTextField7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(sexojTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 364, 210, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Email");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 147, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Grupo Sanguíneo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 191, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Cidade");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 235, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Endereço");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 279, -1, -1));

        emailjTextField8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(emailjTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 144, 214, -1));

        grupoSangjTextField9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        grupoSangjTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupoSangjTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(grupoSangjTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 188, 214, -1));

        cidadejTextField10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(cidadejTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 232, 214, -1));

        enderecojTextArea1.setColumns(20);
        enderecojTextArea1.setRows(5);
        jScrollPane1.setViewportView(enderecojTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 276, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 408, 735, 10));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgbs/img/delete.png"))); // NOI18N
        jButton2.setText("Remover");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 436, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgbs/img/Update details.png"))); // NOI18N
        jButton3.setText("Resetar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 436, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgbs/img/Exit application.png"))); // NOI18N
        jButton4.setText("Sair");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 436, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgbs/img/fundo2.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefonejTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonejTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonejTextField6ActionPerformed

    private void datajTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datajTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datajTextField5ActionPerformed

    private void grupoSangjTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupoSangjTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grupoSangjTextField9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new RemoverDoador().setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String idDoador = IdDoadorjTextField1.getText();
        
        try{
            Connection con = ConexaoMysql.getConexaoMySQL();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from doador where IDDOADOR = " + idDoador);
            
            if(rs.next()){
                nomejTextField2.setText(rs.getString(2));
                nomePaijTextField3.setText(rs.getString(3));
                nomeMaejTextField4.setText(rs.getString(4));
                datajTextField5.setText(rs.getString(5));
                telefonejTextField6.setText(rs.getString(6));
                sexojTextField7.setText(rs.getString(7));
                emailjTextField8.setText(rs.getString(8));
                grupoSangjTextField9.setText(rs.getString(9));
                cidadejTextField10.setText(rs.getString(10));
                enderecojTextArea1.setText(rs.getString(11));
                IdDoadorjTextField1.setEditable(false);
            }else{
                JOptionPane.showMessageDialog(null, "ID Inexistente");
            }
        }catch(Exception e){
            
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String idDoador = IdDoadorjTextField1.getText();
        String nome = nomejTextField2.getText();
        String nomePai = nomePaijTextField3.getText();
        String nomeMae= nomeMaejTextField4.getText();
        String data = datajTextField5.getText();
        String telefone = telefonejTextField6.getText();
        String sexo = sexojTextField7.getText();
        String email = emailjTextField8.getText();
        String grupoSangue = grupoSangjTextField9.getText();
        String cidade = cidadejTextField10.getText();
        String endereco = enderecojTextArea1.getText();
        
        try{
            Connection con = ConexaoMysql.getConexaoMySQL();
            PreparedStatement ps = con.prepareStatement("delete from doador where IDDOADOR = " + idDoador);
            
            
            
            ps.executeUpdate();
            ps.close();
            
            JOptionPane.showMessageDialog(null, "Remoção Realizada com Sucesso");
            setVisible(false);
            new RemoverDoador().setVisible(true);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoverDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoverDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoverDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoverDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoverDoador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdDoadorjTextField1;
    private javax.swing.JTextField cidadejTextField10;
    private javax.swing.JTextField datajTextField5;
    private javax.swing.JTextField emailjTextField8;
    private javax.swing.JTextArea enderecojTextArea1;
    private javax.swing.JTextField grupoSangjTextField9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField nomeMaejTextField4;
    private javax.swing.JTextField nomePaijTextField3;
    private javax.swing.JTextField nomejTextField2;
    private javax.swing.JTextField sexojTextField7;
    private javax.swing.JTextField telefonejTextField6;
    // End of variables declaration//GEN-END:variables
}
