/*doador*/
create table DOADOR(
	IDDOADOR INT(10) PRIMARY KEY,
	NOME VARCHAR(100),
	NOMEDOPAI VARCHAR(100),
	NOMEDAMAE VARCHAR(100),
	DATAANIVERSARIO VARCHAR(20),
	NUMEROTELEFONE VARCHAR(20),
	SEXO VARCHAR(20),
	EMAIL VARCHAR(100),
	GRUPOSANGUINEO VARCHAR(10),
	CIDADE VARCHAR(100),
	ENDERECO VARCHAR(500)
);


/*estoque de sangue*/
create table ESTOQUEDESANGUE(
	GRUPOSANGUINEO VARCHAR(20),
	QUANTIDADE INT(10)
);